### PR TITLE
Add ability to pass options to the constructor.

### PR DESCRIPTION
**Pull request by gianchub**
This simple PR amends the code adding the ability to pass options to the `Redis` class.

### CODE REVIEW

**Comment by gianchub** [comment]
Hey Eugene, we're using your dep at Sohonet.com. We always customise it in order to pass extra options in, so I thought it might be good to do it for all the users of this library, and I created this PR.

Please let me know if there is anything you don't like, or if there are any issues with it.

Kind regards,
Fabrizio

**Comment by etataurov** [comment]
@gianchub Nice. Thanks for PR!
I'll prepare PyPI release

**Comment by gianchub** [comment]
Thank you, much appreciated :)

**Comment by etataurov** [comment]
PyPI release is live https://pypi.python.org/pypi/nameko-redis

**Comment by gianchub** [comment]
Lovely, thank you very much @etataurov :)

**Pull request merged**
